common:
    model:
        name: votenet
        task_type: Sunrgbd
        net_type: votenet
        num_target: 256
        num_input_channel: 1
        vote_factor: 1
        cluster_sampling: vote_fps
        loss_type: NMS # NMS
    logs:
        base_logger:
            path: log/log.txt
        tensorboard_logger:
            path: log
    snapshot:
        save_path: snapshot
    load:
        load: False
        path: ./ckpt_best_model.pth.tar
        type: recover
train:
    batch_size: 8
    workers: 8
    dataset:
        name: Sunrgbd
        split_set: train
        # split_set: val
        # data_path: C:\Users\ZLC\Desktop\pycodes\data\scannet_train_detection_data
        data_path: /mnt/lustre/liujie4/big/
        # data_path: /data1/zhaolichen/data/scannet_train_detection_data
        augment: True
        # use_color: True
        use_height: True  # use it as feature
        use_v1: True
    optimizer:
        name: myAdamW
        betas: [0.9, 0.999]
        eps: 0.00000001
        weight_decay: 0.0001
    lr_scheduler:
        type: cosine
        T_max: 200000
        base_lr: 0.001
        eta_min: 0.0001
    transform: None # TODO
    runner:
        name: iteration
        max_iter: 200000
        # test and save
        test_freq: 5000
        save_freq: 200000
        log_freq: 10
        snapshot_save_path: snapshot
test:
    batch_size: 8
    workers: 4
    dataset:
        valset:
            name: Sunrgbd
            split_set: val
            # data_path: /data1/zhaolichen/data/scannet_train_detection_data
            data_path: /mnt/lustre/liujie4/big/
            # use_color: True
            use_height: True  # use it as feature
            use_v1: True
